orders_warehouse_dbt:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1234
      dbname: dbt
      schema: warehouse

  target: dev
